name: Extract Data

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
  

jobs:

  run_orchestrator:
    env:
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
        DB_DATABASE_NAME: ${{ vars.DB_DATABASE_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_ID: ${{ vars.DB_ID }}
        DB_REGION: ${{ vars.DB_REGION}}
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Run Orchestrator Extract
        run: echo "Hello $DB_USERNAME. $BUILD. Using $DB_HOST $DB_PORT"
        env:
          BUILD: 'We are currently running the Build job'
          
          
