name: Extract Data

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run_orchestrator:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --no-dev

      - name: Run Orchestrator Extract
        run: uv run python main.py
        env:
          DB_HOST:     ${{ vars.DB_HOST }}
          DB_PORT:     ${{ vars.DB_PORT }}
          DB_USER:     ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME:     ${{ vars.DB_NAME }}
