name: Run Orchestrator every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_orchestrator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Orchestrator
      run: |
        python orchestrator.py

        git config --global user.email "humbertoaldemir@gmail.com"
        git config --global user.name "aldemirneto"
        git checkout main
        git merge --no-ff your-branch
        git push