name: Run Orchestrator every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  
jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Orchestrator Scrape
        run: |
          python orchestrator_scrape.py
          
  run_transform:
    runs-on: ubuntu-latest
    needs: run_scraper
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Orchestrator Transform
        run: |
          python orchestrator_transform.py
      
  commit_changes:
    runs-on: ubuntu-latest
    needs: [run_scraper, run_transform]
    steps:
      - name: Initialize Git repository
        run: |
          git init
      - name: Configure Git
        run: |
          git config --global user.email "humbertoaldemir@gmail.com"
          git config --global user.name "aldemirneto"
      - name: Commit and push changes to main branch
        run: |
          git add .
          git commit -m "Inserindo dados"
          git push origin main
