name: Run Orchestrator every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_orchestrator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create and checkout your-branch
      run: |
        git checkout -b your-branch
    - name: Run Orchestrator
      run: |
        python orchestrator.py
    - name: Commit and push changes to your-branch
      run: |
        git add .
        git commit -m "Added changes from orchestrator.py"
        git push -u origin your-branch
    - name: Checkout main
      run: |
        git checkout main
