name: Transform Data

on:
  push:
    branches:
     - 'main'
    paths:
      - '**imoveis.csv'
      - '**imoveis_aluguel.csv'


  workflow_dispatch:
  

jobs:
  run_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Orchestrator Transform
        run: |
          python orchestrator_transform.py
      - name: Configure Git
        run: |
          git config --global user.email "humbertoaldemir@gmail.com"
          git config --global user.name "aldemirneto"
      - name: Check for changes
        id: git-status
        run: |
          changes=$(git status --porcelain)
          if [[ -z "$changes" ]]; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi
      - name: Commit and push changes to main branch
        if: steps.git-status.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Tratando dados"
          git push origin main
